delete
from vocabulary_sentence;
delete
from sentence_tense;
delete
from sentence_history;
delete
from user_vocabulary;
delete
from users;
delete
from sentence;
delete
from vocabulary;

ALTER TABLE "public"."vocabulary"
    DROP COLUMN "speech_part_id";
drop table speech_part;
drop table sentence_tense;
drop table tense;
drop table duration;
drop table time;

CREATE TABLE theme_category
(
    id    integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title text NOT NULL
);

INSERT INTO "public"."theme_category"("title") VALUES('🕘 Часи') RETURNING "id", "title";
INSERT INTO "public"."theme_category"("title") VALUES('📍 Прийменники') RETURNING "id", "title";
INSERT INTO "public"."theme_category"("title") VALUES('📚 Складні конструкції') RETURNING "id", "title";


CREATE TABLE theme
(
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   text NOT NULL,
    caption text NOT NULL DEFAULT '--'::text,
    category_id integer REFERENCES theme_category (id)
);

CREATE TABLE theme_theme
(
    id       integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    theme_id integer REFERENCES theme (id),
    rely_id  integer REFERENCES theme (id)
);

ALTER TABLE "public"."sentence"
    ADD COLUMN "theme_id" integer NOT NULL,
    ADD FOREIGN KEY ("theme_id") REFERENCES "public"."theme" ("id");

ALTER TABLE "public"."vocabulary"
    ADD COLUMN "second" text NOT NULL,
    ADD COLUMN "third"  text NOT NULL;


ALTER TABLE "public"."sentence" ADD COLUMN "explanation" text DEFAULT '--';
ALTER TABLE "public"."sentence_history" ADD COLUMN "respond_time" integer NOT NULL;
ALTER TABLE "public"."vocabulary_sentence" ADD COLUMN "is_modal" boolean NOT NULL DEFAULT 'false';