CREATE TABLE subscription_plan
(
    id               integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name             text             NOT NULL,
    price            double precision NOT NULL,
    duration_days    integer          NOT NULL
);

INSERT INTO "public"."subscription_plan"("name", "price", "duration_days")
VALUES ('БЕЗКОШТОВНА', 0, 3);
INSERT INTO "public"."subscription_plan"("name", "price", "duration_days")
VALUES ('3 МІСЯЦІ', 172, 93);
INSERT INTO "public"."subscription_plan"("name", "price", "duration_days")
VALUES ('6 МІСЯЦІ', 312, 186);

CREATE TABLE checkout
(
    id                   uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    subscription_plan_id integer NOT NULL REFERENCES subscription_plan (id),
    user_id              integer NOT NULL REFERENCES users (id)
);

CREATE TABLE subscription
(
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at                   timestamp without time zone NOT NULL DEFAULT now(),
    valid_due            timestamp without time zone NOT NULL,
    user_id              integer                     NOT NULL REFERENCES users (id),
    checkout_id          uuid REFERENCES checkout (id),
    subscription_plan_id integer REFERENCES subscription_plan (id)
);
